plugins {
	id 'fabric-loom' version '1.15-SNAPSHOT'
	id 'java-library'
	id 'maven-publish'
	id 'org.quiltmc.gradle.licenser' version '1.1.+'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

// This field defines the Java version your mod target.
def targetJavaVersion = 21

boolean isMCVersionNonRelease() {
	def mc = libs.versions.minecraft.get()
	return mc.matches('^\\d\\dw\\d\\d[a-z]$') || mc.matches('\\d+\\.\\d+-(pre|rc)(\\d+)')
}

String getMCVersionString() {
	def mc = libs.versions.minecraft.get()
	if (isMCVersionNonRelease()) {
		return mc
	}
	def version = mc.split('\\.')
	return version[0] + '.' + version[1]
}

loom {
	accessWidenerPath = file('src/main/resources/quakecraft.accesswidener')
}

repositories {
	mavenLocal()
	mavenCentral()
	maven {
		name 'Nucleoid'
		url 'https://maven.nucleoid.xyz/'
	}
	maven {
		name 'Gegy'
		url 'https://maven.gegy.dev/'
	}
}

configurations {
	shadow
	api.extendsFrom shadow
}

dependencies {
	minecraft libs.minecraft
	modImplementation libs.fabric.loader

	// mappings libs.minecraft.mappings
	mappings "net.fabricmc:yarn:1.21.11+build.4"
	// Fabric API.
	modImplementation libs.fabric.api

	// Plasmid.
	modImplementation libs.nucleoid.plasmid
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'

	it.options.release.set(targetJavaVersion)
}

processResources {
	inputs.property 'version', project.version

	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

license {
	rule file('HEADER')
	include '**/*.java'
}
